import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  Modal,
  FlatList,
  Image,
  Dimensions,
  Alert,
  Platform,
  I18nManager,
} from 'react-native';
import CountryFlag from 'react-native-country-flag';
import { CAIRO_FONT_FAMILY, globalTextStyles } from '../../styles/globalStyles';
import CustomBottomSheet from './CustomBottomSheet';

interface Country {
  code: string;
  name: string;
  nameAr: string;
  flag: string;
  dialCode: string;
  pattern: string;
  maxLength: number;
}

interface CustomPhoneInputProps {
  value: string;
  onChangeText: (text: string) => void;
  onCountryChange?: (country: Country) => void;
  placeholder?: string;
  error?: boolean;
  disabled?: boolean;
  style?: any;
  initialCountry?: Country;
  inputContainerStyle?: any;
}

export const COUNTRIES: Country[] = [
  {
    code: 'SA',
    name: 'Saudi Arabia',
    nameAr: 'المملكة العربية السعودية',
    flag: '🇸🇦',
    dialCode: '+966',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    nameAr: 'الإمارات العربية المتحدة',
    flag: '🇦🇪',
    dialCode: '+971',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'QA',
    name: 'Qatar',
    nameAr: 'قطر',
    flag: '🇶🇦',
    dialCode: '+974',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'KW',
    name: 'Kuwait',
    nameAr: 'الكويت',
    flag: '🇰🇼',
    dialCode: '+965',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'BH',
    name: 'Bahrain',
    nameAr: 'البحرين',
    flag: '🇧🇭',
    dialCode: '+973',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'OM',
    name: 'Oman',
    nameAr: 'عُمان',
    flag: '🇴🇲',
    dialCode: '+968',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'JO',
    name: 'Jordan',
    nameAr: 'الأردن',
    flag: '🇯🇴',
    dialCode: '+962',
    pattern: '# #### ####',
    maxLength: 9,
  },
  {
    code: 'LB',
    name: 'Lebanon',
    nameAr: 'لبنان',
    flag: '🇱🇧',
    dialCode: '+961',
    pattern: '## ### ###',
    maxLength: 8,
  },
  {
    code: 'EG',
    name: 'Egypt',
    nameAr: 'مصر',
    flag: '🇪🇬',
    dialCode: '+20',
    pattern: '## #### ####',
    maxLength: 10,
  },
  {
    code: 'IQ',
    name: 'Iraq',
    nameAr: 'العراق',
    flag: '🇮🇶',
    dialCode: '+964',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'IR',
    name: 'Iran',
    nameAr: 'إيران',
    flag: '🇮🇷',
    dialCode: '+98',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'TR',
    name: 'Turkey',
    nameAr: 'تركيا',
    flag: '🇹🇷',
    dialCode: '+90',
    pattern: '### ### ####',
    maxLength: 10,
  },
  // Additional countries (alphabetically by code)
  {
    code: 'AD',
    name: 'Andorra',
    nameAr: 'أندورا',
    flag: '🇦🇩',
    dialCode: '+376',
    pattern: '### ###',
    maxLength: 6,
  },
  {
    code: 'AF',
    name: 'Afghanistan',
    nameAr: 'أفغانستان',
    flag: '🇦🇫',
    dialCode: '+93',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'AG',
    name: 'Antigua and Barbuda',
    nameAr: 'أنتيغوا وبربودا',
    flag: '🇦🇬',
    dialCode: '+1268',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'AI',
    name: 'Anguilla',
    nameAr: 'أنغويلا',
    flag: '🇦🇮',
    dialCode: '+1264',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'AL',
    name: 'Albania',
    nameAr: 'ألبانيا',
    flag: '🇦🇱',
    dialCode: '+355',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'AM',
    name: 'Armenia',
    nameAr: 'أرمينيا',
    flag: '🇦🇲',
    dialCode: '+374',
    pattern: '## ######',
    maxLength: 8,
  },
  {
    code: 'AO',
    name: 'Angola',
    nameAr: 'أنغولا',
    flag: '🇦🇴',
    dialCode: '+244',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'AQ',
    name: 'Antarctica',
    nameAr: 'القارة القطبية الجنوبية',
    flag: '🇦🇶',
    dialCode: '+672',
    pattern: '### ###',
    maxLength: 6,
  },
  {
    code: 'AR',
    name: 'Argentina',
    nameAr: 'الأرجنتين',
    flag: '🇦🇷',
    dialCode: '+54',
    pattern: '## #### ####',
    maxLength: 10,
  },
  {
    code: 'AS',
    name: 'American Samoa',
    nameAr: 'ساموا الأمريكية',
    flag: '🇦🇸',
    dialCode: '+1684',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'AT',
    name: 'Austria',
    nameAr: 'النمسا',
    flag: '🇦🇹',
    dialCode: '+43',
    pattern: '### ######',
    maxLength: 9,
  },
  {
    code: 'AU',
    name: 'Australia',
    nameAr: 'أستراليا',
    flag: '🇦🇺',
    dialCode: '+61',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'AW',
    name: 'Aruba',
    nameAr: 'أروبا',
    flag: '🇦🇼',
    dialCode: '+297',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'AX',
    name: 'Åland Islands',
    nameAr: 'جزر آلاند',
    flag: '🇦🇽',
    dialCode: '+358',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'AZ',
    name: 'Azerbaijan',
    nameAr: 'أذربيجان',
    flag: '🇦🇿',
    dialCode: '+994',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    nameAr: 'البوسنة والهرسك',
    flag: '🇧🇦',
    dialCode: '+387',
    pattern: '## ### ###',
    maxLength: 8,
  },
  {
    code: 'BB',
    name: 'Barbados',
    nameAr: 'بربادوس',
    flag: '🇧🇧',
    dialCode: '+1246',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    nameAr: 'بنغلاديش',
    flag: '🇧🇩',
    dialCode: '+880',
    pattern: '#### ######',
    maxLength: 10,
  },
  {
    code: 'BE',
    name: 'Belgium',
    nameAr: 'بلجيكا',
    flag: '🇧🇪',
    dialCode: '+32',
    pattern: '### ## ## ##',
    maxLength: 9,
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
    nameAr: 'بوركينا فاسو',
    flag: '🇧🇫',
    dialCode: '+226',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'BG',
    name: 'Bulgaria',
    nameAr: 'بلغاريا',
    flag: '🇧🇬',
    dialCode: '+359',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'BI',
    name: 'Burundi',
    nameAr: 'بوروندي',
    flag: '🇧🇮',
    dialCode: '+257',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'BJ',
    name: 'Benin',
    nameAr: 'بنين',
    flag: '🇧🇯',
    dialCode: '+229',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'BL',
    name: 'Saint Barthélemy',
    nameAr: 'سان بارتيليمي',
    flag: '🇧🇱',
    dialCode: '+590',
    pattern: '### ## ## ##',
    maxLength: 9,
  },
  {
    code: 'BM',
    name: 'Bermuda',
    nameAr: 'برمودا',
    flag: '🇧🇲',
    dialCode: '+1441',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'BN',
    name: 'Brunei',
    nameAr: 'بروناي',
    flag: '🇧🇳',
    dialCode: '+673',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'BO',
    name: 'Bolivia',
    nameAr: 'بوليفيا',
    flag: '🇧🇴',
    dialCode: '+591',
    pattern: '########',
    maxLength: 8,
  },
  {
    code: 'BQ',
    name: 'Caribbean Netherlands',
    nameAr: 'هولندا الكاريبية',
    flag: '🇧🇶',
    dialCode: '+599',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'BR',
    name: 'Brazil',
    nameAr: 'البرازيل',
    flag: '🇧🇷',
    dialCode: '+55',
    pattern: '## #####-####',
    maxLength: 11,
  },
  {
    code: 'BS',
    name: 'Bahamas',
    nameAr: 'جزر البهاما',
    flag: '🇧🇸',
    dialCode: '+1242',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'BT',
    name: 'Bhutan',
    nameAr: 'بوتان',
    flag: '🇧🇹',
    dialCode: '+975',
    pattern: '## ### ###',
    maxLength: 8,
  },
  {
    code: 'BV',
    name: 'Bouvet Island',
    nameAr: 'جزيرة بوفيت',
    flag: '🇧🇻',
    dialCode: '+47',
    pattern: '### ## ###',
    maxLength: 8,
  },
  {
    code: 'BW',
    name: 'Botswana',
    nameAr: 'بوتسوانا',
    flag: '🇧🇼',
    dialCode: '+267',
    pattern: '## ### ###',
    maxLength: 7,
  },
  {
    code: 'BY',
    name: 'Belarus',
    nameAr: 'بيلاروس',
    flag: '🇧🇾',
    dialCode: '+375',
    pattern: '## ###-##-##',
    maxLength: 9,
  },
  {
    code: 'BZ',
    name: 'Belize',
    nameAr: 'بليز',
    flag: '🇧🇿',
    dialCode: '+501',
    pattern: '###-####',
    maxLength: 7,
  },
  {
    code: 'CA',
    name: 'Canada',
    nameAr: 'كندا',
    flag: '🇨🇦',
    dialCode: '+1',
    pattern: '(###) ###-####',
    maxLength: 10,
  },
  {
    code: 'CC',
    name: 'Cocos Islands',
    nameAr: 'جزر كوكوس',
    flag: '🇨🇨',
    dialCode: '+61',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'CD',
    name: 'Democratic Republic of the Congo',
    nameAr: 'جمهورية الكونغو الديمقراطية',
    flag: '🇨🇩',
    dialCode: '+243',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'CF',
    name: 'Central African Republic',
    nameAr: 'جمهورية أفريقيا الوسطى',
    flag: '🇨🇫',
    dialCode: '+236',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'CG',
    name: 'Republic of the Congo',
    nameAr: 'جمهورية الكونغو',
    flag: '🇨🇬',
    dialCode: '+242',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'CH',
    name: 'Switzerland',
    nameAr: 'سويسرا',
    flag: '🇨🇭',
    dialCode: '+41',
    pattern: '## ### ## ##',
    maxLength: 9,
  },
  {
    code: 'CI',
    name: 'Ivory Coast',
    nameAr: 'ساحل العاج',
    flag: '🇨🇮',
    dialCode: '+225',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'CK',
    name: 'Cook Islands',
    nameAr: 'جزر كوك',
    flag: '🇨🇰',
    dialCode: '+682',
    pattern: '## ###',
    maxLength: 5,
  },
  {
    code: 'CL',
    name: 'Chile',
    nameAr: 'تشيلي',
    flag: '🇨🇱',
    dialCode: '+56',
    pattern: '# #### ####',
    maxLength: 9,
  },
  {
    code: 'CM',
    name: 'Cameroon',
    nameAr: 'الكاميرون',
    flag: '🇨🇲',
    dialCode: '+237',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'CN',
    name: 'China',
    nameAr: 'الصين',
    flag: '🇨🇳',
    dialCode: '+86',
    pattern: '### #### ####',
    maxLength: 11,
  },
  {
    code: 'CO',
    name: 'Colombia',
    nameAr: 'كولومبيا',
    flag: '🇨🇴',
    dialCode: '+57',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'CR',
    name: 'Costa Rica',
    nameAr: 'كوستاريكا',
    flag: '🇨🇷',
    dialCode: '+506',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'CU',
    name: 'Cuba',
    nameAr: 'كوبا',
    flag: '🇨🇺',
    dialCode: '+53',
    pattern: '# ### ####',
    maxLength: 8,
  },
  {
    code: 'CV',
    name: 'Cape Verde',
    nameAr: 'الرأس الأخضر',
    flag: '🇨🇻',
    dialCode: '+238',
    pattern: '### ## ##',
    maxLength: 7,
  },
  {
    code: 'CW',
    name: 'Curaçao',
    nameAr: 'كوراساو',
    flag: '🇨🇼',
    dialCode: '+599',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'CX',
    name: 'Christmas Island',
    nameAr: 'جزيرة الكريسماس',
    flag: '🇨🇽',
    dialCode: '+61',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'CY',
    name: 'Cyprus',
    nameAr: 'قبرص',
    flag: '🇨🇾',
    dialCode: '+357',
    pattern: '## ######',
    maxLength: 8,
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    nameAr: 'جمهورية التشيك',
    flag: '🇨🇿',
    dialCode: '+420',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'DE',
    name: 'Germany',
    nameAr: 'ألمانيا',
    flag: '🇩🇪',
    dialCode: '+49',
    pattern: '#### #######',
    maxLength: 11,
  },
  {
    code: 'DJ',
    name: 'Djibouti',
    nameAr: 'جيبوتي',
    flag: '🇩🇯',
    dialCode: '+253',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'DK',
    name: 'Denmark',
    nameAr: 'الدنمارك',
    flag: '🇩🇰',
    dialCode: '+45',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'DM',
    name: 'Dominica',
    nameAr: 'دومينيكا',
    flag: '🇩🇲',
    dialCode: '+1767',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'DO',
    name: 'Dominican Republic',
    nameAr: 'جمهورية الدومينيكان',
    flag: '🇩🇴',
    dialCode: '+1',
    pattern: '(###) ###-####',
    maxLength: 10,
  },
  {
    code: 'DZ',
    name: 'Algeria',
    nameAr: 'الجزائر',
    flag: '🇩🇿',
    dialCode: '+213',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'EC',
    name: 'Ecuador',
    nameAr: 'الإكوادور',
    flag: '🇪🇨',
    dialCode: '+593',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'EE',
    name: 'Estonia',
    nameAr: 'إستونيا',
    flag: '🇪🇪',
    dialCode: '+372',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'EH',
    name: 'Western Sahara',
    nameAr: 'الصحراء الغربية',
    flag: '🇪🇭',
    dialCode: '+212',
    pattern: '##-####-###',
    maxLength: 9,
  },
  {
    code: 'ER',
    name: 'Eritrea',
    nameAr: 'إريتريا',
    flag: '🇪🇷',
    dialCode: '+291',
    pattern: '# ### ###',
    maxLength: 7,
  },
  {
    code: 'ES',
    name: 'Spain',
    nameAr: 'إسبانيا',
    flag: '🇪🇸',
    dialCode: '+34',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'ET',
    name: 'Ethiopia',
    nameAr: 'إثيوبيا',
    flag: '🇪🇹',
    dialCode: '+251',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'FI',
    name: 'Finland',
    nameAr: 'فنلندا',
    flag: '🇫🇮',
    dialCode: '+358',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'FJ',
    name: 'Fiji',
    nameAr: 'فيجي',
    flag: '🇫🇯',
    dialCode: '+679',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'FK',
    name: 'Falkland Islands',
    nameAr: 'جزر فوكلاند',
    flag: '🇫🇰',
    dialCode: '+500',
    pattern: '#####',
    maxLength: 5,
  },
  {
    code: 'FM',
    name: 'Micronesia',
    nameAr: 'ميكرونيزيا',
    flag: '🇫🇲',
    dialCode: '+691',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'FO',
    name: 'Faroe Islands',
    nameAr: 'جزر فارو',
    flag: '🇫🇴',
    dialCode: '+298',
    pattern: '######',
    maxLength: 6,
  },
  {
    code: 'FR',
    name: 'France',
    nameAr: 'فرنسا',
    flag: '🇫🇷',
    dialCode: '+33',
    pattern: '## ## ## ## ##',
    maxLength: 10,
  },
  {
    code: 'GA',
    name: 'Gabon',
    nameAr: 'الغابون',
    flag: '🇬🇦',
    dialCode: '+241',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    nameAr: 'المملكة المتحدة',
    flag: '🇬🇧',
    dialCode: '+44',
    pattern: '#### ######',
    maxLength: 10,
  },
  {
    code: 'GD',
    name: 'Grenada',
    nameAr: 'غرينادا',
    flag: '🇬🇩',
    dialCode: '+1473',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'GE',
    name: 'Georgia',
    nameAr: 'جورجيا',
    flag: '🇬🇪',
    dialCode: '+995',
    pattern: '### ## ## ##',
    maxLength: 9,
  },
  {
    code: 'GF',
    name: 'French Guiana',
    nameAr: 'غويانا الفرنسية',
    flag: '🇬🇫',
    dialCode: '+594',
    pattern: '### ## ## ##',
    maxLength: 9,
  },
  {
    code: 'GG',
    name: 'Guernsey',
    nameAr: 'غيرنزي',
    flag: '🇬🇬',
    dialCode: '+44',
    pattern: '#### ######',
    maxLength: 10,
  },
  {
    code: 'GH',
    name: 'Ghana',
    nameAr: 'غانا',
    flag: '🇬🇭',
    dialCode: '+233',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'GI',
    name: 'Gibraltar',
    nameAr: 'جبل طارق',
    flag: '🇬🇮',
    dialCode: '+350',
    pattern: '### #####',
    maxLength: 8,
  },
  {
    code: 'GL',
    name: 'Greenland',
    nameAr: 'غرينلاند',
    flag: '🇬🇱',
    dialCode: '+299',
    pattern: '## ## ##',
    maxLength: 6,
  },
  {
    code: 'GM',
    name: 'Gambia',
    nameAr: 'غامبيا',
    flag: '🇬🇲',
    dialCode: '+220',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'GN',
    name: 'Guinea',
    nameAr: 'غينيا',
    flag: '🇬🇳',
    dialCode: '+224',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'GP',
    name: 'Guadeloupe',
    nameAr: 'غوادلوب',
    flag: '🇬🇵',
    dialCode: '+590',
    pattern: '### ## ## ##',
    maxLength: 9,
  },
  {
    code: 'GQ',
    name: 'Equatorial Guinea',
    nameAr: 'غينيا الاستوائية',
    flag: '🇬🇶',
    dialCode: '+240',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'GR',
    name: 'Greece',
    nameAr: 'اليونان',
    flag: '🇬🇷',
    dialCode: '+30',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    nameAr: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
    flag: '🇬🇸',
    dialCode: '+500',
    pattern: '#####',
    maxLength: 5,
  },
  {
    code: 'GT',
    name: 'Guatemala',
    nameAr: 'غواتيمالا',
    flag: '🇬🇹',
    dialCode: '+502',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'GU',
    name: 'Guam',
    nameAr: 'غوام',
    flag: '🇬🇺',
    dialCode: '+1671',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'GW',
    name: 'Guinea-Bissau',
    nameAr: 'غينيا بيساو',
    flag: '🇬🇼',
    dialCode: '+245',
    pattern: '# ######',
    maxLength: 7,
  },
  {
    code: 'GY',
    name: 'Guyana',
    nameAr: 'غيانا',
    flag: '🇬🇾',
    dialCode: '+592',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    nameAr: 'هونغ كونغ',
    flag: '🇭🇰',
    dialCode: '+852',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'HM',
    name: 'Heard Island and McDonald Islands',
    nameAr: 'جزيرة هيرد وجزر ماكدونالد',
    flag: '🇭🇲',
    dialCode: '+672',
    pattern: '### ###',
    maxLength: 6,
  },
  {
    code: 'HN',
    name: 'Honduras',
    nameAr: 'هندوراس',
    flag: '🇭🇳',
    dialCode: '+504',
    pattern: '####-####',
    maxLength: 8,
  },
  {
    code: 'HR',
    name: 'Croatia',
    nameAr: 'كرواتيا',
    flag: '🇭🇷',
    dialCode: '+385',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'HT',
    name: 'Haiti',
    nameAr: 'هايتي',
    flag: '🇭🇹',
    dialCode: '+509',
    pattern: '## ## ####',
    maxLength: 8,
  },
  {
    code: 'HU',
    name: 'Hungary',
    nameAr: 'المجر',
    flag: '🇭🇺',
    dialCode: '+36',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'ID',
    name: 'Indonesia',
    nameAr: 'إندونيسيا',
    flag: '🇮🇩',
    dialCode: '+62',
    pattern: '###-###-####',
    maxLength: 10,
  },
  {
    code: 'IE',
    name: 'Ireland',
    nameAr: 'أيرلندا',
    flag: '🇮🇪',
    dialCode: '+353',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'IL',
    name: 'Israel',
    nameAr: 'إسرائيل',
    flag: '🇮🇱',
    dialCode: '+972',
    pattern: '##-###-####',
    maxLength: 9,
  },
  {
    code: 'IM',
    name: 'Isle of Man',
    nameAr: 'جزيرة مان',
    flag: '🇮🇲',
    dialCode: '+44',
    pattern: '#### ######',
    maxLength: 10,
  },
  {
    code: 'IN',
    name: 'India',
    nameAr: 'الهند',
    flag: '🇮🇳',
    dialCode: '+91',
    pattern: '##### #####',
    maxLength: 10,
  },
  {
    code: 'IO',
    name: 'British Indian Ocean Territory',
    nameAr: 'إقليم المحيط الهندي البريطاني',
    flag: '🇮🇴',
    dialCode: '+246',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'IS',
    name: 'Iceland',
    nameAr: 'آيسلندا',
    flag: '🇮🇸',
    dialCode: '+354',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'IT',
    name: 'Italy',
    nameAr: 'إيطاليا',
    flag: '🇮🇹',
    dialCode: '+39',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'JE',
    name: 'Jersey',
    nameAr: 'جيرزي',
    flag: '🇯🇪',
    dialCode: '+44',
    pattern: '#### ######',
    maxLength: 10,
  },
  {
    code: 'JM',
    name: 'Jamaica',
    nameAr: 'جامايكا',
    flag: '🇯🇲',
    dialCode: '+1876',
    pattern: '###-####',
    maxLength: 7,
  },
  {
    code: 'JP',
    name: 'Japan',
    nameAr: 'اليابان',
    flag: '🇯🇵',
    dialCode: '+81',
    pattern: '##-####-####',
    maxLength: 10,
  },
  {
    code: 'KE',
    name: 'Kenya',
    nameAr: 'كينيا',
    flag: '🇰🇪',
    dialCode: '+254',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'KG',
    name: 'Kyrgyzstan',
    nameAr: 'قيرغيزستان',
    flag: '🇰🇬',
    dialCode: '+996',
    pattern: '### ## ## ##',
    maxLength: 9,
  },
  {
    code: 'KH',
    name: 'Cambodia',
    nameAr: 'كمبوديا',
    flag: '🇰🇭',
    dialCode: '+855',
    pattern: '## ### ###',
    maxLength: 9,
  },
  {
    code: 'KI',
    name: 'Kiribati',
    nameAr: 'كيريباتي',
    flag: '🇰🇮',
    dialCode: '+686',
    pattern: '## ###',
    maxLength: 5,
  },
  {
    code: 'KM',
    name: 'Comoros',
    nameAr: 'جزر القمر',
    flag: '🇰🇲',
    dialCode: '+269',
    pattern: '## ## ##',
    maxLength: 7,
  },
  {
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    nameAr: 'سانت كيتس ونيفيس',
    flag: '🇰🇳',
    dialCode: '+1869',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'KP',
    name: 'North Korea',
    nameAr: 'كوريا الشمالية',
    flag: '🇰🇵',
    dialCode: '+850',
    pattern: '###-###-####',
    maxLength: 10,
  },
  {
    code: 'KR',
    name: 'South Korea',
    nameAr: 'كوريا الجنوبية',
    flag: '🇰🇷',
    dialCode: '+82',
    pattern: '##-####-####',
    maxLength: 10,
  },
  {
    code: 'KY',
    name: 'Cayman Islands',
    nameAr: 'جزر كايمان',
    flag: '🇰🇾',
    dialCode: '+1345',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'KZ',
    name: 'Kazakhstan',
    nameAr: 'كازاخستان',
    flag: '🇰🇿',
    dialCode: '+7',
    pattern: '### ### ## ##',
    maxLength: 10,
  },
  {
    code: 'LA',
    name: 'Laos',
    nameAr: 'لاوس',
    flag: '🇱🇦',
    dialCode: '+856',
    pattern: '## ## ### ###',
    maxLength: 10,
  },
  {
    code: 'LC',
    name: 'Saint Lucia',
    nameAr: 'سانت لوسيا',
    flag: '🇱🇨',
    dialCode: '+1758',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'LI',
    name: 'Liechtenstein',
    nameAr: 'ليختنشتاين',
    flag: '🇱🇮',
    dialCode: '+423',
    pattern: '### ## ##',
    maxLength: 7,
  },
  {
    code: 'LK',
    name: 'Sri Lanka',
    nameAr: 'سريلانكا',
    flag: '🇱🇰',
    dialCode: '+94',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'LR',
    name: 'Liberia',
    nameAr: 'ليبيريا',
    flag: '🇱🇷',
    dialCode: '+231',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'LS',
    name: 'Lesotho',
    nameAr: 'ليسوتو',
    flag: '🇱🇸',
    dialCode: '+266',
    pattern: '## ### ####',
    maxLength: 8,
  },
  {
    code: 'LT',
    name: 'Lithuania',
    nameAr: 'ليتوانيا',
    flag: '🇱🇹',
    dialCode: '+370',
    pattern: '### #####',
    maxLength: 8,
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    nameAr: 'لوكسمبورغ',
    flag: '🇱🇺',
    dialCode: '+352',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'LV',
    name: 'Latvia',
    nameAr: 'لاتفيا',
    flag: '🇱🇻',
    dialCode: '+371',
    pattern: '## ### ###',
    maxLength: 8,
  },
  {
    code: 'LY',
    name: 'Libya',
    nameAr: 'ليبيا',
    flag: '🇱🇾',
    dialCode: '+218',
    pattern: '##-###-####',
    maxLength: 9,
  },
  {
    code: 'MA',
    name: 'Morocco',
    nameAr: 'المغرب',
    flag: '🇲🇦',
    dialCode: '+212',
    pattern: '##-####-###',
    maxLength: 9,
  },
  {
    code: 'MC',
    name: 'Monaco',
    nameAr: 'موناكو',
    flag: '🇲🇨',
    dialCode: '+377',
    pattern: '## ## ## ##',
    maxLength: 9,
  },
  {
    code: 'MD',
    name: 'Moldova',
    nameAr: 'مولدوفا',
    flag: '🇲🇩',
    dialCode: '+373',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'ME',
    name: 'Montenegro',
    nameAr: 'الجبل الأسود',
    flag: '🇲🇪',
    dialCode: '+382',
    pattern: '## ### ###',
    maxLength: 8,
  },
  {
    code: 'MF',
    name: 'Saint Martin',
    nameAr: 'سانت مارتن',
    flag: '🇲🇫',
    dialCode: '+590',
    pattern: '### ## ## ##',
    maxLength: 9,
  },
  {
    code: 'MG',
    name: 'Madagascar',
    nameAr: 'مدغشقر',
    flag: '🇲🇬',
    dialCode: '+261',
    pattern: '## ## ### ##',
    maxLength: 9,
  },
  {
    code: 'MH',
    name: 'Marshall Islands',
    nameAr: 'جزر مارشال',
    flag: '🇲🇭',
    dialCode: '+692',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'MK',
    name: 'North Macedonia',
    nameAr: 'مقدونيا الشمالية',
    flag: '🇲🇰',
    dialCode: '+389',
    pattern: '## ### ###',
    maxLength: 8,
  },
  {
    code: 'ML',
    name: 'Mali',
    nameAr: 'مالي',
    flag: '🇲🇱',
    dialCode: '+223',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'MM',
    name: 'Myanmar',
    nameAr: 'ميانمار',
    flag: '🇲🇲',
    dialCode: '+95',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'MN',
    name: 'Mongolia',
    nameAr: 'منغوليا',
    flag: '🇲🇳',
    dialCode: '+976',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'MO',
    name: 'Macao',
    nameAr: 'ماكاو',
    flag: '🇲🇴',
    dialCode: '+853',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'MP',
    name: 'Northern Mariana Islands',
    nameAr: 'جزر ماريانا الشمالية',
    flag: '🇲🇵',
    dialCode: '+1670',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'MQ',
    name: 'Martinique',
    nameAr: 'مارتينيك',
    flag: '🇲🇶',
    dialCode: '+596',
    pattern: '### ## ## ##',
    maxLength: 9,
  },
  {
    code: 'MR',
    name: 'Mauritania',
    nameAr: 'موريتانيا',
    flag: '🇲🇷',
    dialCode: '+222',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'MS',
    name: 'Montserrat',
    nameAr: 'مونتسيرات',
    flag: '🇲🇸',
    dialCode: '+1664',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'MT',
    name: 'Malta',
    nameAr: 'مالطا',
    flag: '🇲🇹',
    dialCode: '+356',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'MU',
    name: 'Mauritius',
    nameAr: 'موريشيوس',
    flag: '🇲🇺',
    dialCode: '+230',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'MV',
    name: 'Maldives',
    nameAr: 'جزر المالديف',
    flag: '🇲🇻',
    dialCode: '+960',
    pattern: '###-####',
    maxLength: 7,
  },
  {
    code: 'MW',
    name: 'Malawi',
    nameAr: 'مالاوي',
    flag: '🇲🇼',
    dialCode: '+265',
    pattern: '# #### ####',
    maxLength: 9,
  },
  {
    code: 'MX',
    name: 'Mexico',
    nameAr: 'المكسيك',
    flag: '🇲🇽',
    dialCode: '+52',
    pattern: '## #### ####',
    maxLength: 10,
  },
  {
    code: 'MY',
    name: 'Malaysia',
    nameAr: 'ماليزيا',
    flag: '🇲🇾',
    dialCode: '+60',
    pattern: '#-### ####',
    maxLength: 9,
  },
  {
    code: 'MZ',
    name: 'Mozambique',
    nameAr: 'موزمبيق',
    flag: '🇲🇿',
    dialCode: '+258',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'NA',
    name: 'Namibia',
    nameAr: 'ناميبيا',
    flag: '🇳🇦',
    dialCode: '+264',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'NC',
    name: 'New Caledonia',
    nameAr: 'كاليدونيا الجديدة',
    flag: '🇳🇨',
    dialCode: '+687',
    pattern: '##.##.##',
    maxLength: 6,
  },
  {
    code: 'NE',
    name: 'Niger',
    nameAr: 'النيجر',
    flag: '🇳🇪',
    dialCode: '+227',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'NF',
    name: 'Norfolk Island',
    nameAr: 'جزيرة نورفولك',
    flag: '🇳🇫',
    dialCode: '+672',
    pattern: '### ###',
    maxLength: 6,
  },
  {
    code: 'NG',
    name: 'Nigeria',
    nameAr: 'نيجيريا',
    flag: '🇳🇬',
    dialCode: '+234',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'NI',
    name: 'Nicaragua',
    nameAr: 'نيكاراغوا',
    flag: '🇳🇮',
    dialCode: '+505',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'NL',
    name: 'Netherlands',
    nameAr: 'هولندا',
    flag: '🇳🇱',
    dialCode: '+31',
    pattern: '# #### ####',
    maxLength: 9,
  },
  {
    code: 'NO',
    name: 'Norway',
    nameAr: 'النرويج',
    flag: '🇳🇴',
    dialCode: '+47',
    pattern: '### ## ###',
    maxLength: 8,
  },
  {
    code: 'NP',
    name: 'Nepal',
    nameAr: 'نيبال',
    flag: '🇳🇵',
    dialCode: '+977',
    pattern: '###-###-####',
    maxLength: 10,
  },
  {
    code: 'NR',
    name: 'Nauru',
    nameAr: 'ناورو',
    flag: '🇳🇷',
    dialCode: '+674',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'NU',
    name: 'Niue',
    nameAr: 'نيوي',
    flag: '🇳🇺',
    dialCode: '+683',
    pattern: '####',
    maxLength: 4,
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    nameAr: 'نيوزيلندا',
    flag: '🇳🇿',
    dialCode: '+64',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'PA',
    name: 'Panama',
    nameAr: 'بنما',
    flag: '🇵🇦',
    dialCode: '+507',
    pattern: '####-####',
    maxLength: 8,
  },
  {
    code: 'PE',
    name: 'Peru',
    nameAr: 'بيرو',
    flag: '🇵🇪',
    dialCode: '+51',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'PF',
    name: 'French Polynesia',
    nameAr: 'بولينيزيا الفرنسية',
    flag: '🇵🇫',
    dialCode: '+689',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'PG',
    name: 'Papua New Guinea',
    nameAr: 'بابوا غينيا الجديدة',
    flag: '🇵🇬',
    dialCode: '+675',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'PH',
    name: 'Philippines',
    nameAr: 'الفلبين',
    flag: '🇵🇭',
    dialCode: '+63',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'PK',
    name: 'Pakistan',
    nameAr: 'باكستان',
    flag: '🇵🇰',
    dialCode: '+92',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'PL',
    name: 'Poland',
    nameAr: 'بولندا',
    flag: '🇵🇱',
    dialCode: '+48',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'PM',
    name: 'Saint Pierre and Miquelon',
    nameAr: 'سانت بيير وميكلون',
    flag: '🇵🇲',
    dialCode: '+508',
    pattern: '## ## ##',
    maxLength: 6,
  },
  {
    code: 'PN',
    name: 'Pitcairn',
    nameAr: 'بيتكيرن',
    flag: '🇵🇳',
    dialCode: '+64',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'PR',
    name: 'Puerto Rico',
    nameAr: 'بورتوريكو',
    flag: '🇵🇷',
    dialCode: '+1',
    pattern: '(###) ###-####',
    maxLength: 10,
  },
  {
    code: 'PS',
    name: 'Palestine',
    nameAr: 'فلسطين',
    flag: '🇵🇸',
    dialCode: '+970',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'PT',
    name: 'Portugal',
    nameAr: 'البرتغال',
    flag: '🇵🇹',
    dialCode: '+351',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'PW',
    name: 'Palau',
    nameAr: 'بالاو',
    flag: '🇵🇼',
    dialCode: '+680',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'PY',
    name: 'Paraguay',
    nameAr: 'باراغواي',
    flag: '🇵🇾',
    dialCode: '+595',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'RE',
    name: 'Réunion',
    nameAr: 'ريونيون',
    flag: '🇷🇪',
    dialCode: '+262',
    pattern: '### ## ## ##',
    maxLength: 9,
  },
  {
    code: 'RO',
    name: 'Romania',
    nameAr: 'رومانيا',
    flag: '🇷🇴',
    dialCode: '+40',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'RS',
    name: 'Serbia',
    nameAr: 'صربيا',
    flag: '🇷🇸',
    dialCode: '+381',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'RU',
    name: 'Russia',
    nameAr: 'روسيا',
    flag: '🇷🇺',
    dialCode: '+7',
    pattern: '### ###-##-##',
    maxLength: 10,
  },
  {
    code: 'RW',
    name: 'Rwanda',
    nameAr: 'رواندا',
    flag: '🇷🇼',
    dialCode: '+250',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'SB',
    name: 'Solomon Islands',
    nameAr: 'جزر سليمان',
    flag: '🇸🇧',
    dialCode: '+677',
    pattern: '#####',
    maxLength: 5,
  },
  {
    code: 'SC',
    name: 'Seychelles',
    nameAr: 'سيشل',
    flag: '🇸🇨',
    dialCode: '+248',
    pattern: '# ## ## ##',
    maxLength: 7,
  },
  {
    code: 'SD',
    name: 'Sudan',
    nameAr: 'السودان',
    flag: '🇸🇩',
    dialCode: '+249',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'SE',
    name: 'Sweden',
    nameAr: 'السويد',
    flag: '🇸🇪',
    dialCode: '+46',
    pattern: '##-### ## ##',
    maxLength: 9,
  },
  {
    code: 'SG',
    name: 'Singapore',
    nameAr: 'سنغافورة',
    flag: '🇸🇬',
    dialCode: '+65',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'SH',
    name: 'Saint Helena',
    nameAr: 'سانت هيلينا',
    flag: '🇸🇭',
    dialCode: '+290',
    pattern: '####',
    maxLength: 4,
  },
  {
    code: 'SI',
    name: 'Slovenia',
    nameAr: 'سلوفينيا',
    flag: '🇸🇮',
    dialCode: '+386',
    pattern: '## ### ###',
    maxLength: 8,
  },
  {
    code: 'SJ',
    name: 'Svalbard and Jan Mayen',
    nameAr: 'سفالبارد ويان ماين',
    flag: '🇸🇯',
    dialCode: '+47',
    pattern: '### ## ###',
    maxLength: 8,
  },
  {
    code: 'SK',
    name: 'Slovakia',
    nameAr: 'سلوفاكيا',
    flag: '🇸🇰',
    dialCode: '+421',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'SL',
    name: 'Sierra Leone',
    nameAr: 'سيراليون',
    flag: '🇸🇱',
    dialCode: '+232',
    pattern: '## ######',
    maxLength: 8,
  },
  {
    code: 'SM',
    name: 'San Marino',
    nameAr: 'سان مارينو',
    flag: '🇸🇲',
    dialCode: '+378',
    pattern: '#### ######',
    maxLength: 10,
  },
  {
    code: 'SN',
    name: 'Senegal',
    nameAr: 'السنغال',
    flag: '🇸🇳',
    dialCode: '+221',
    pattern: '## ### ## ##',
    maxLength: 9,
  },
  {
    code: 'SO',
    name: 'Somalia',
    nameAr: 'الصومال',
    flag: '🇸🇴',
    dialCode: '+252',
    pattern: '# #######',
    maxLength: 8,
  },
  {
    code: 'SR',
    name: 'Suriname',
    nameAr: 'سورينام',
    flag: '🇸🇷',
    dialCode: '+597',
    pattern: '###-####',
    maxLength: 7,
  },
  {
    code: 'SS',
    name: 'South Sudan',
    nameAr: 'جنوب السودان',
    flag: '🇸🇸',
    dialCode: '+211',
    pattern: '#### ######',
    maxLength: 10,
  },
  {
    code: 'ST',
    name: 'São Tomé and Príncipe',
    nameAr: 'ساو تومي وبرينسيب',
    flag: '🇸🇹',
    dialCode: '+239',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'SV',
    name: 'El Salvador',
    nameAr: 'السلفادور',
    flag: '🇸🇻',
    dialCode: '+503',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'SX',
    name: 'Sint Maarten',
    nameAr: 'سينت مارتن',
    flag: '🇸🇽',
    dialCode: '+1721',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'SY',
    name: 'Syria',
    nameAr: 'سوريا',
    flag: '🇸🇾',
    dialCode: '+963',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'SZ',
    name: 'Eswatini',
    nameAr: 'إسواتيني',
    flag: '🇸🇿',
    dialCode: '+268',
    pattern: '## ## ####',
    maxLength: 8,
  },
  {
    code: 'TC',
    name: 'Turks and Caicos Islands',
    nameAr: 'جزر تركس وكايكوس',
    flag: '🇹🇨',
    dialCode: '+1649',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'TD',
    name: 'Chad',
    nameAr: 'تشاد',
    flag: '🇹🇩',
    dialCode: '+235',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'TF',
    name: 'French Southern Territories',
    nameAr: 'الأراضي الفرنسية الجنوبية',
    flag: '🇹🇫',
    dialCode: '+262',
    pattern: '### ## ## ##',
    maxLength: 9,
  },
  {
    code: 'TG',
    name: 'Togo',
    nameAr: 'توغو',
    flag: '🇹🇬',
    dialCode: '+228',
    pattern: '## ## ## ##',
    maxLength: 8,
  },
  {
    code: 'TH',
    name: 'Thailand',
    nameAr: 'تايلاند',
    flag: '🇹🇭',
    dialCode: '+66',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'TJ',
    name: 'Tajikistan',
    nameAr: 'طاجيكستان',
    flag: '🇹🇯',
    dialCode: '+992',
    pattern: '### ## ####',
    maxLength: 9,
  },
  {
    code: 'TK',
    name: 'Tokelau',
    nameAr: 'توكيلاو',
    flag: '🇹🇰',
    dialCode: '+690',
    pattern: '####',
    maxLength: 4,
  },
  {
    code: 'TL',
    name: 'East Timor',
    nameAr: 'تيمور الشرقية',
    flag: '🇹🇱',
    dialCode: '+670',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'TM',
    name: 'Turkmenistan',
    nameAr: 'تركمانستان',
    flag: '🇹🇲',
    dialCode: '+993',
    pattern: '## ##-####',
    maxLength: 8,
  },
  {
    code: 'TN',
    name: 'Tunisia',
    nameAr: 'تونس',
    flag: '🇹🇳',
    dialCode: '+216',
    pattern: '## ### ###',
    maxLength: 8,
  },
  {
    code: 'TO',
    name: 'Tonga',
    nameAr: 'تونغا',
    flag: '🇹🇴',
    dialCode: '+676',
    pattern: '#####',
    maxLength: 5,
  },
  {
    code: 'TT',
    name: 'Trinidad and Tobago',
    nameAr: 'ترينيداد وتوباغو',
    flag: '🇹🇹',
    dialCode: '+1868',
    pattern: '###-####',
    maxLength: 7,
  },
  {
    code: 'TV',
    name: 'Tuvalu',
    nameAr: 'توفالو',
    flag: '🇹🇻',
    dialCode: '+688',
    pattern: '#####',
    maxLength: 5,
  },
  {
    code: 'TW',
    name: 'Taiwan',
    nameAr: 'تايوان',
    flag: '🇹🇼',
    dialCode: '+886',
    pattern: '#### ####',
    maxLength: 9,
  },
  {
    code: 'TZ',
    name: 'Tanzania',
    nameAr: 'تنزانيا',
    flag: '🇹🇿',
    dialCode: '+255',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'UA',
    name: 'Ukraine',
    nameAr: 'أوكرانيا',
    flag: '🇺🇦',
    dialCode: '+380',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'UG',
    name: 'Uganda',
    nameAr: 'أوغندا',
    flag: '🇺🇬',
    dialCode: '+256',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'UM',
    name: 'United States Minor Outlying Islands',
    nameAr: 'جزر الولايات المتحدة الصغيرة النائية',
    flag: '🇺🇲',
    dialCode: '+1',
    pattern: '(###) ###-####',
    maxLength: 10,
  },
  {
    code: 'US',
    name: 'United States',
    nameAr: 'الولايات المتحدة',
    flag: '🇺🇸',
    dialCode: '+1',
    pattern: '(###) ###-####',
    maxLength: 10,
  },
  {
    code: 'UY',
    name: 'Uruguay',
    nameAr: 'أوروغواي',
    flag: '🇺🇾',
    dialCode: '+598',
    pattern: '#### ####',
    maxLength: 8,
  },
  {
    code: 'UZ',
    name: 'Uzbekistan',
    nameAr: 'أوزبكستان',
    flag: '🇺🇿',
    dialCode: '+998',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'VA',
    name: 'Vatican City',
    nameAr: 'الفاتيكان',
    flag: '🇻🇦',
    dialCode: '+39',
    pattern: '### ### ####',
    maxLength: 10,
  },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    nameAr: 'سانت فنسنت والغرينادين',
    flag: '🇻🇨',
    dialCode: '+1784',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'VE',
    name: 'Venezuela',
    nameAr: 'فنزويلا',
    flag: '🇻🇪',
    dialCode: '+58',
    pattern: '###-###.####',
    maxLength: 10,
  },
  {
    code: 'VG',
    name: 'British Virgin Islands',
    nameAr: 'جزر العذراء البريطانية',
    flag: '🇻🇬',
    dialCode: '+1284',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'VI',
    name: 'United States Virgin Islands',
    nameAr: 'جزر العذراء الأمريكية',
    flag: '🇻🇮',
    dialCode: '+1340',
    pattern: '### ####',
    maxLength: 7,
  },
  {
    code: 'VN',
    name: 'Vietnam',
    nameAr: 'فيتنام',
    flag: '🇻🇳',
    dialCode: '+84',
    pattern: '### #### ###',
    maxLength: 10,
  },
  {
    code: 'VU',
    name: 'Vanuatu',
    nameAr: 'فانواتو',
    flag: '🇻🇺',
    dialCode: '+678',
    pattern: '#####',
    maxLength: 5,
  },
  {
    code: 'WF',
    name: 'Wallis and Futuna',
    nameAr: 'واليس وفوتونا',
    flag: '🇼🇫',
    dialCode: '+681',
    pattern: '## ## ##',
    maxLength: 6,
  },
  {
    code: 'WS',
    name: 'Samoa',
    nameAr: 'ساموا',
    flag: '🇼🇸',
    dialCode: '+685',
    pattern: '## ####',
    maxLength: 6,
  },
  {
    code: 'XK',
    name: 'Kosovo',
    nameAr: 'كوسوفو',
    flag: '🇽🇰',
    dialCode: '+383',
    pattern: '## ### ###',
    maxLength: 8,
  },
  {
    code: 'YE',
    name: 'Yemen',
    nameAr: 'اليمن',
    flag: '🇾🇪',
    dialCode: '+967',
    pattern: '# ### ####',
    maxLength: 8,
  },
  {
    code: 'YT',
    name: 'Mayotte',
    nameAr: 'مايوت',
    flag: '🇾🇹',
    dialCode: '+262',
    pattern: '### ## ## ##',
    maxLength: 9,
  },
  {
    code: 'ZA',
    name: 'South Africa',
    nameAr: 'جنوب أفريقيا',
    flag: '🇿🇦',
    dialCode: '+27',
    pattern: '## ### ####',
    maxLength: 9,
  },
  {
    code: 'ZM',
    name: 'Zambia',
    nameAr: 'زامبيا',
    flag: '🇿🇲',
    dialCode: '+260',
    pattern: '### ### ###',
    maxLength: 9,
  },
  {
    code: 'ZW',
    name: 'Zimbabwe',
    nameAr: 'زيمبابوي',
    flag: '🇿🇼',
    dialCode: '+263',
    pattern: '# #######',
    maxLength: 9,
  }
];

const CustomPhoneInput: React.FC<CustomPhoneInputProps> = ({
  value,
  onChangeText,
  onCountryChange,
  placeholder = 'Enter phone number',
  error,
  disabled = false,
  style,
  initialCountry,
  inputContainerStyle,
}) => {
  const [selectedCountry, setSelectedCountry] = useState<Country>(initialCountry || COUNTRIES[0]); // Use initialCountry or default to Saudi Arabia
  const [showCountryModal, setShowCountryModal] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [filteredCountries, setFilteredCountries] = useState<Country[]>(COUNTRIES);
  const inputRef = useRef<TextInput>(null);
  const isRTL = I18nManager.isRTL;

  useEffect(() => {
    // Filter countries based on search query
    if (searchQuery.trim() === '') {
      setFilteredCountries(COUNTRIES);
    } else {
      const filtered = COUNTRIES.filter(
        country =>
          country.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
          country.nameAr.includes(searchQuery) ||
          country.dialCode.includes(searchQuery)
      );
      setFilteredCountries(filtered);
    }
  }, [searchQuery]);

  useEffect(() => {
    setSelectedCountry(initialCountry || COUNTRIES[0]);
  }, [initialCountry]);

  const handleCountrySelect = (country: Country) => {
    setSelectedCountry(country);
    setShowCountryModal(false);
    setSearchQuery('');
    onCountryChange?.(country);
    
    // Clear the phone number when country changes
    onChangeText('');
    
    // Focus on input after country selection
    setTimeout(() => {
      inputRef.current?.focus();
    }, 300);
  };

  const formatPhoneNumber = (input: string): string => {
    const digits = input.replace(/\D/g, '');
    
    if (digits.length === 0) return '';
    
    const pattern = selectedCountry.pattern;
    let formatted = '';
    let digitIndex = 0;
    
    for (let i = 0; i < pattern.length && digitIndex < digits.length; i++) {
      if (pattern[i] === '#') {
        formatted += digits[digitIndex];
        digitIndex++;
      } else {
        formatted += pattern[i];
      }
    }
    
    return formatted;
  };

  const handlePhoneNumberChange = (text: string) => {
    const formatted = formatPhoneNumber(text);
    onChangeText(formatted);
  };

  const validatePhoneNumber = (): boolean => {
    const digits = value.replace(/\D/g, '');
    return digits.length === selectedCountry.maxLength;
  };

  const renderCountryItem = ({ item }: { item: Country }) => (
    <TouchableOpacity
      style={[
        styles.countryItem,
        selectedCountry.code === item.code && styles.selectedCountryItem,
      ]}
      onPress={() => handleCountrySelect(item)}
    >
      <View style={styles.countryItemContent}>
        <View style={[styles.flagContainer, {marginLeft: 12}]}>
          <CountryFlag isoCode={item.code} size={16} />
        </View>
        <View style={styles.countryInfo}>
          <Text style={styles.countryName}>{item.name}</Text>
          <Text style={styles.countryNameAr}>{item.nameAr}</Text>
        </View>
        <Text style={styles.countryCodeModal}>{item.dialCode}</Text>
      </View>
    </TouchableOpacity>
  );

  return (
    <View style={[styles.container, style]}>
      {/* Phone Input Field */}
      <View style={[styles.inputContainer,inputContainerStyle, error && styles.inputError]}>
        {/* Country Selector */}
        <TouchableOpacity
          style={styles.countrySelector}
          onPress={() => {
            setShowCountryModal(true);
          }}
          disabled={disabled}
        >
          <View style={styles.flagContainer}>
            <CountryFlag isoCode={selectedCountry.code} size={16} />
          </View>
          <Text style={styles.countryCode}>{selectedCountry.dialCode}</Text>
          <Text style={styles.dropdownIcon}>▼</Text>
        </TouchableOpacity>

        {/* Separator */}
        <View style={styles.separator} />

        {/* Phone Number Input */}
        <TextInput
          ref={inputRef}
          style={[styles.phoneInput, Platform.OS === 'android' && styles.androidPhoneInput]}
          value={value}
          onChangeText={handlePhoneNumberChange}
          placeholder={placeholder}
          placeholderTextColor="#999"
          keyboardType="phone-pad"
          maxLength={selectedCountry.pattern.length}
          editable={!disabled}
        />
      </View>

      {/* Country Selection Modal */}
      <CustomBottomSheet
        visible={showCountryModal}
        onClose={() => setShowCountryModal(false)}
        height="65%"
        backdropClickable={true}
        showHandle={true}
      >
        <View style={styles.modalContainer}>
          {/* Search Bar */}
          <View style={styles.searchContainer}>
            <TextInput
              style={styles.searchInput}
              placeholder="Search country..."
              value={searchQuery}
              onChangeText={setSearchQuery}
              placeholderTextColor="#999"
            />
          </View>

          {/* Countries List */}
          <FlatList
            data={filteredCountries}
            renderItem={renderCountryItem}
            keyExtractor={(item) => item.code}
            showsVerticalScrollIndicator={false}
            contentContainerStyle={styles.countriesList}
            keyboardShouldPersistTaps="handled"
            initialNumToRender={10}
            maxToRenderPerBatch={10}
            windowSize={10}
          />
        </View>
      </CustomBottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    width: '100%',
    
  },
  inputContainer: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    paddingVertical: 8,
    minHeight: 44,
  },
  inputError: {
    borderColor: '#FF3B30',
  },
  countrySelector: {
    flexDirection:I18nManager.isRTL?'row-reverse':'row',
    alignItems: 'center',
  },
  countryFlag: {
    fontSize: 20,
    marginLeft: 6,
  },
  countryCode: {
    fontSize: 16,
    fontFamily: CAIRO_FONT_FAMILY.semiBold,
    lineHeight: Platform.OS === 'ios' ? 0 : 20,
    color: '#191919',
    marginLeft: 4,
  },
  dropdownIcon: {
    fontSize: 12,
    color: '#666',
  },
  separator: {
    width: 1,
    height: 24,
    backgroundColor: '#E0E0E0',
    marginHorizontal: 4,
  },
  phoneInput: {
    flex: 1,
    ...globalTextStyles.bodyMedium,
    color: '#333',
    padding: 0,
    textAlign: 'left',
    // Force LTR direction for phone numbers regardless of app language
    writingDirection: 'ltr',
  },
  androidPhoneInput: {
    // Android-specific LTR forcing
    textAlign: 'left',
    textAlignVertical: 'center',
    // Force LTR layout on Android
    start: 0,
    end: undefined,
  },
  patternHint: {
    ...globalTextStyles.bodySmall,
    color: '#666',
    marginTop: 8,
    marginLeft: 16,
    // Force LTR direction for pattern hint
    writingDirection: 'ltr',
    textAlign: 'left',
  },
  errorText: {
    ...globalTextStyles.bodySmall,
    color: '#FF3B30',
    marginTop: 8,
    marginLeft: 16,
    // Force LTR direction for error text
    writingDirection: 'ltr',
    textAlign: 'left',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  searchContainer: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    ...globalTextStyles.bodyMedium,
    color: '#333',
  },
  countriesList: {
    paddingBottom: 20,
  },
  countryItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  selectedCountryItem: {
    backgroundColor: '#F8F9FA',
  },
  countryItemContent: {
    flexDirection: I18nManager.isRTL?'row-reverse':'row',
    alignItems: 'center',
  },
  flagContainer: {
    marginLeft: 6,
    marginRight: 4,
    overflow: 'hidden',
    borderRadius: 2,
  },
  countryInfo: {
    flex: 1,
    marginLeft: 12,
  },
  countryName: {
    ...globalTextStyles.bodyMedium,
    fontWeight: '500',
    color: '#333',
    marginBottom: 2,
    textAlign: I18nManager.isRTL?'right':'left',
  },
  countryNameAr: {
    ...globalTextStyles.bodySmall,
    color: '#666',
    textAlign: I18nManager.isRTL?'right':'left',
  },
  countryCodeModal: {
    ...globalTextStyles.bodyMedium,
    fontWeight: '600',
    color: '#666',
  },
  // Fallback modal styles
  fallbackModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  fallbackModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '70%',
  },
  fallbackModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  fallbackModalTitle: {
    ...globalTextStyles.h4,
    fontWeight: '600',
    color: '#333',
  },
  fallbackModalClose: {
    fontSize: 24,
    color: '#666',
    padding: 4,
  },
});

export default CustomPhoneInput; 